server:
  port: 8080
  
zuul: 
  routes: 
    books.url: http://localhost:9000
    
ribbon: 
  eureka: 
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
 
spring:
  application:
    name: zuul
    
info: 
  appname: zuul