server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
spring:
  application:
    name: ip-location-server
    
info: 
  appname: ip-location-server